openapi: "3.0.3"
info:
  title: Nishiki Web API
  description: Nishiki
  version: 1.0.0
servers:
  - url: www
tags:
  - name: user
    description: user of Nishiki system
paths:
  /auth/me:
    get:
      summary: Get a User ID
      description: The user is identified by the token.
      tags:
        - auth
      responses:
        "200":
          description: User ID
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserId"
  /users:
    post:
      description: Create a new user
      tags:
        - user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - emailAddress
              properties:
                name:
                  description: username. this name is not provided, the name will be set as a default value.
                  type: string
                  nullable: true
                emailAddress:
                  type: string
      responses:
        "201":
          description: user created
  /users/{userId}:
    get:
      description: Get a user
      tags:
        - user
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      responses:
        "200":
          description: get user information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
    put:
      description: Update a user data
      tags:
        - user
      parameters:
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  description: user's name
                  type: string
      responses:
        "202":
          description: update user's information
        "401":
          description: try to change other user's information
  /containers:
    get:
      summary: Get a list of the user's container
      description: The requesting user is identified by the token of request.
      tags:
        - container
      responses:
        "200":
          description: Get containers linked to the user
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/Container"
    post:
      description: create a new container
      tags:
        - container
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                groupId:
                  type: string
                  nullable: false
                  example: groupId
                name:
                  type: string
                  nullable: true
                  example: my-container
      responses:
        "201":
          description: creation complete
          content:
            application/json:
              schema:
                type: object
                properties:
                  containerId:
                    type: string
                    description: generated container ID
                    example: containerId
  /containers/{containerId}:
    get:
      description: get a container information
      tags:
        - container
      parameters:
        - name: containerId
          in: path
          description: ID of container
          required: true
          schema:
            type: string
      responses:
        "200":
          description: get a container
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Container"
  /containers/{containerId}/foods:
    post:
      description: add a new food
      tags:
        - container
      parameters:
        - name: containerId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - "name"
              properties:
                name:
                  type: string
                  nullable: false
                  example: bouillon
                unit:
                  type: string
                  nullable: true
                  example: l
                quantity:
                  type: integer
                  nullable: true
                  example: 1
                expiry:
                  type: string
                  format: date-time
                  nullable: true
                  example: 1970-01-01T00:00:00.000Z
      responses:
        "201":
          description: adding the food complete
          content:
            application/json:
              schema:
                type: object
                properties:
                  foodId:
                    type: string
                    example: foodId
  /containers/{containerId}/foods/{foodId}:
    put:
      description: update a food
      tags:
        - container
      parameters:
        - name: containerId
          in: path
          description: ID of container
          required: true
          schema:
            type: string
        - name: foodId
          in: path
          description: ID of food
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
              properties:
                name:
                  type: string
                  nullable: false
                  example: bouillon
                unit:
                  type: string
                  nullable: true
                  example: l
                quantity:
                  type: integer
                  nullable: true
                  example: 1
                expiry:
                  type: string
                  format: date-time
                  nullable: true
                  example: 1970-01-01T00:00:00.000Z
      responses:
        "202":
          description: update complete
    delete:
      description: delete a food
      tags:
        - container
      parameters:
        - name: containerId
          in: path
          description: ID of container
          required: true
          schema:
            type: string
        - name: foodId
          in: path
          description: ID of food
          required: true
          schema:
            type: string
      responses:
        "202":
          description: deletion complete
  /groups:
    get:
      summary: Get a list of groups linked to a user
      description: The requesting user is detected by the token.
      tags:
        - group
      responses:
        "200":
          description: a list of groups information
          content:
            application/json:
              schema:
                type: object
                properties:
                  groups:
                    type: array
                    items:
                      $ref: "#/components/schemas/Group"
    post:
      description: create a new group
      tags:
        - group
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                groupName:
                  type: string
                  nullable: true
                  example: group1
      responses:
        "201":
          description: generated group ID
          content:
            application/json:
              schema:
                type: object
                properties:
                  groupId:
                    type: string
                    example: group1
  /groups/{groupId}:
    get:
      description: Get a group
      tags:
        - group
      parameters:
        - name: groupId
          in: path
          description: ID of group
          required: true
          schema:
            type: string
      responses:
        "200":
          description: get a group information
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Group"
  /groups/{groupId}/containers:
    get:
      description: get a list of the group's container
      tags:
        - group
      parameters:
        - name: groupId
          in: path
          description: ID of group
          required: true
          schema:
            type: string
      responses:
        "200":
          description: get group's containers
          content:
            application/json:
              schema:
                type: object
                properties:
                  containers:
                    type: array
                    items:
                      $ref: "#/components/schemas/Container"
  /groups/{groupId}/users:
    get:
      description: Get a list of users in the group
      tags:
        - group
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: list of users
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: "#/components/schemas/User"
  /groups/{groupId}/users/{userId}:
    put:
      tags:
        - group
      parameters:
        - name: groupId
          in: path
          description: ID of group
          required: true
          schema:
            type: string
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      description: add the target user ID in the path parameter
      responses:
        "202":
          description: add a user to the group
    delete:
      tags:
        - group
      parameters:
        - name: groupId
          in: path
          description: ID of group
          required: true
          schema:
            type: string
        - name: userId
          in: path
          description: ID of user
          required: true
          schema:
            type: string
      description: add the target user ID in the path parameter
      responses:
        "202":
          description: deletion complete
components:
  schemas:
    UserId:
      type: object
      properties:
        userId:
          type: string
          format: uuid
          example: 2dd6dd70-5b3a-4329-9b70-01fd18c4b23c
    User:
      type: object
      properties:
        id:
          type: string
          nullable: false
          format: uuid
          example: 679adc58-b03a-4fb6-993b-c72404087375
        name:
          type: string
          nullable: false
          example: John
    Container:
      type: object
      properties:
        id:
          type: string
          nullable: false
          format: uuid
          example: 939a4c50-ee7b-4558-b8d5-371514e77bed
        name:
          type: string
          nullable: false
          example: container1
        group:
          type: string
          nullable: false
          example: groupId
        foods:
          type: array
          nullable: false
          items:
            $ref: "#/components/schemas/Food"
    Group:
      type: object
      properties:
        groupId:
          type: string
          nullable: false
          format: uuid
          example: 82597aad-0d1b-4672-8b9a-fd3764cb9928
        groupName:
          type: string
          nullable: false
          example: group1
    Food:
      type: object
      properties:
        id:
          type: string
          example: 3c740136-58b7-4c3d-9548-fc0a4d3b3ef4
          format: uuid
          nullable: false
        name:
          type: string
          example: arugula
          nullable: false
        quantity:
          type: integer
          format: int64
          nullable: true
          example: 1
        unit:
          type: string
          nullable: true
          example: kg
        expiry:
          type: string
          nullable: true
          format: date-time
          example: 1970-01-01T00:00:00.000Z
